// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtjXSETy2mST3SiJae89NaR1XGU-dXwu0',
    appId: '1:710984403215:web:f33ee1cfdddb3020b4167a',
    messagingSenderId: '710984403215',
    projectId: 'chat-app-85413',
    authDomain: 'chat-app-85413.firebaseapp.com',
    storageBucket: 'chat-app-85413.firebasestorage.app',
    measurementId: 'G-VHQZY0K9BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJNWSf6Zh2BOprykZtEQSJT77U2m9AMuQ',
    appId: '1:710984403215:android:cb5b333a0f6a6766b4167a',
    messagingSenderId: '710984403215',
    projectId: 'chat-app-85413',
    storageBucket: 'chat-app-85413.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCoUeJouZjVUr3SU1m67lZF9sx76trXSM',
    appId: '1:710984403215:ios:3e1ec90aa4ff6073b4167a',
    messagingSenderId: '710984403215',
    projectId: 'chat-app-85413',
    storageBucket: 'chat-app-85413.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCoUeJouZjVUr3SU1m67lZF9sx76trXSM',
    appId: '1:710984403215:ios:3e1ec90aa4ff6073b4167a',
    messagingSenderId: '710984403215',
    projectId: 'chat-app-85413',
    storageBucket: 'chat-app-85413.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtjXSETy2mST3SiJae89NaR1XGU-dXwu0',
    appId: '1:710984403215:web:d18e94cf3babbcdcb4167a',
    messagingSenderId: '710984403215',
    projectId: 'chat-app-85413',
    authDomain: 'chat-app-85413.firebaseapp.com',
    storageBucket: 'chat-app-85413.firebasestorage.app',
    measurementId: 'G-CHHECXXSLF',
  );
}
